apiVersion: apps/v1
kind: Deployment
metadata:
   name: catalog-api
spec:
  replicas: 1
  selector:
     matchLabels:
        app: catalog-api
  template:
     metadata:
        labels:
           app: catalog-api
     spec:
        initContainers:
          - name: wait-for-postgres
            image: busybox
            command:
               [
                  "sh",
                  "-c",
                  "until nc -z postgres 5432; do echo waiting for db; sleep 2; done;"
               ]
        imagePullSecrets:
           - name: docker-secret
        containers:
           - name: catalog-api
             image: docker.io/amitdhaker/catalog-api:latest
             ports: 
              - containerPort: 8080
             env:
               - name: ASPNETCORE_URLS
                 value: "http://+:8080"
               - name: ConnectionStrings__Database
                 value: "Server=postgres;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true"

  