apiVersion: v1
kind: Service
metadata: 
   name: catalog-api-Service
spec:
   type: LoadBalancer
   selector:
      app: catalog-api
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080