name: Catalog & postgres DB app deployment autometic

on:
    push:
        branches: 
            - main

env:
    AKS_RESOURCE_GROUP: aks-rg
    AKS_CLUSTER_NAME: aks-dev-cluster

jobs:

    build-push-deploy:
        runs-on: ubuntu-latest
        steps:

            # 1. checkout the code
            - name: checkout code
              uses: actions/checkout@v3

            # 2. login to Dockerhub
            - name: Docker login
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            # 3. Build & Push Image
            - name: Build & Push image
              run: |
                 docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/catalog-api:latest -f src/Services/Catalog/Catalog.API/Dockerfile src
                 docker push ${{ secrets.DOCKERHUB_USERNAME }}/catalog-api:latest

            # 4. Login to azure
            - name: Login to Azure
              uses: azure/login@v1
              with: 
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            
            # 5. GET AKS Credentials
            - name: Get AKS Credentials
              run: |
                 az aks get-credentials \
                     --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
                     --name ${{ env.AKS_CLUSTER_NAME }} \
                     --overwrite-existing

            # 6. Create /Update ImagePullSecret (Auto 🔥)
            - name: Create the Docker Secret
              run: |
                kubectl create secret docker-registry docker-secret \
                   --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
                   --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
                   --docker-email=apamitpal6@gmail.com \
                   --dry-run=client -o yaml | kubectl apply -f -



            - name: Deploy PostgreSQL
              run: kubectl apply -f k8s/postgres.yaml

            - name: Wait for PostgreSQL
              run: |
                kubectl wait --for=condition=Ready pod \
                  -l app=postgres \
                  --timeout=300s

            - name: Deploy catalog API
              run: |
                kubectl apply -f k8s/catalog-deployment.yaml
                kubectl apply -f k8s/catalog-service.yaml
   


